version: '2'

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    links:
      - web
      - sockets
  web:
    image: django-channels:latest
    volumes:
      - ./src:/src
    expose:
      - "8000"
    links:
      - redis:redis
    command: uwsgi --http-socket :8000 --module stuff.wsgi
  sockets:
    image: django-channels:latest
    volumes:
      - ./src:/src
    expose:
      - "8001"
    links:
      - redis:redis
    depends_on:
      - workers
    command: daphne stuff.asgi:channel_layer --port 8001 --bind 0.0.0.0 -v2
  workers:
    image: django-channels:latest
    volumes:
      - ./src:/src
    links:
      - redis:redis
    command: python manage.py runworker
  redis:
    image: redis:latest
    expose:
      - "6379"